# Generated by Django 5.1.4 on 2024-12-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10)),
            ],
        ),
    ]
